
export enum TypesOfAttack{
    HTTP_FLOOD = 'HTTP_FLOOD',
    SLOWLORIS = 'SLOWLORIS',
    TLS_FLOOD = 'TLS_FLOOD',
    SSL_FLOOD = "SSL_FLOOD",
    TCP_SYN_FLOOD = 'TCP SYN FLOOD',
    TEAR_DROP_ATTACK = 'TEAR_DROP_ATTACK',
    SMURF_ATTACK = 'SMURF_ATTACK',
    UDP_FLOOD = 'UDP_FLOOD',
    ICMP_FLOOD = 'ICMP_FLOOD',
    DNS_AMPLIFICATION = 'DNS_AMPLIFICATION',
}